name: Build Custom PRoot Environment

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Determine Next Tag
      id: get_next_tag
      run: |
        git fetch --tags
        latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v0.0.0")
        IFS='.' read -r -a version_parts <<< "${latest_tag#v}"
        major=${version_parts[0]}
        minor=${version_parts[1]}
        patch=${version_parts[2]}
        new_patch=$((patch + 1))
        new_tag="v$major.$minor.$new_patch"
        echo "::set-output name=tag::$new_tag"

    - name: Create and Push Tag
      run: |
        new_tag=${{ steps.get_next_tag.outputs.tag }}
        git tag "$new_tag"
        git push origin "$new_tag"

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget tar

    - name: Set up root filesystem
      run: |
        ROOTFS_DIR="./rootfs"
        UBUNTU_VERSION="22.04"
        UBUNTU_BASE_URL="http://cdimage.ubuntu.com/ubuntu-base/releases/$UBUNTU_VERSION/release"
        ARCH=$(uname -m)

        # Configuration
        MAX_RETRIES=50
        TIMEOUT=1
        PROOT_URL="https://raw.githubusercontent.com/foxytouxxx/freeroot/main"
        
        # Validate architecture
        case "$ARCH" in
          x86_64) ARCH_ALT=amd64 ;;
          aarch64) ARCH_ALT=arm64 ;;
          *) echo "Unsupported CPU architecture: $ARCH"; exit 1 ;;
        esac

        # Install Ubuntu root filesystem
        echo "Downloading Ubuntu rootfs..."
        wget --tries="$MAX_RETRIES" --timeout="$TIMEOUT" --no-hsts -O /tmp/rootfs.tar.gz \
          "$UBUNTU_BASE_URL/ubuntu-base-$UBUNTU_VERSION-base-${ARCH_ALT}.tar.gz"

        echo "Creating rootfs directory at $ROOTFS_DIR..."
        mkdir -p "$ROOTFS_DIR"

        echo "Extracting rootfs to $ROOTFS_DIR..."
        tar -xf /tmp/rootfs.tar.gz -C "$ROOTFS_DIR"

    - name: Install proot
      run: |
        ROOTFS_DIR="./rootfs"
        mkdir -p "$ROOTFS_DIR/usr/local/bin"
        wget --tries=50 --timeout=1 --no-hsts -O "$ROOTFS_DIR/usr/local/bin/proot" \
          "$PROOT_URL/proot-${ARCH}"

        chmod 755 "$ROOTFS_DIR/usr/local/bin/proot"

    - name: Configure resolv.conf
      run: |
        ROOTFS_DIR="./rootfs"
        echo "Configuring DNS resolv.conf..."
        echo -e "nameserver 1.1.1.1\nnameserver 1.0.0.1\nnameserver 8.8.8.8\nnameserver 8.8.4.4" \
          > "$ROOTFS_DIR/etc/resolv.conf"

    - name: Install packages inside PRoot
      run: |
        ROOTFS_DIR="./rootfs"
        echo "Installing packages inside PRoot..."
        ./rootfs/usr/local/bin/proot \
          --rootfs="$ROOTFS_DIR" \
          -0 -w "/root" \
          -b /dev -b /sys -b /proc -b /etc/resolv.conf \
          --kill-on-exit \
          /usr/bin/env -i PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
          bash -c "apt-get update -y && apt-get install -y wget libsodium-dev libcurl4-openssl-dev libssl-dev libjansson-dev libomp5"

    - name: Install ccminer and hellminer
      run: |
        ROOTFS_DIR="./rootfs"
        echo "Downloading and installing ccminer..."
        wget https://github.com/Oink70/ccminer-verus/releases/download/v3.8.3a-CPU/ccminer-v3.8.3a-oink_Ubuntu_18.04 -O "$ROOTFS_DIR/opt/ccminer"
        chmod +x "$ROOTFS_DIR/opt/ccminer"

        echo "Downloading and installing hellminer..."
        wget wget -qO- https://github.com/hellcatz/hminer/releases/download/v0.59.1/hellminer_linux64.tar.gz | tar -xvf -C "$ROOTFS_DIR/opt/"
        chmod +x "$ROOTFS_DIR/opt/hellminer"

    - name: Package the root filesystem
      run: |
        ROOTFS_DIR="./rootfs"
        OUTPUT_TAR="./custom-proot.tar.gz"
        tar -czf "$OUTPUT_TAR" --exclude="$OUTPUT_TAR" \
          --exclude="$ROOTFS_DIR/proc/*" --exclude="$ROOTFS_DIR/sys/*" \
          --exclude="$ROOTFS_DIR/dev/*" "$ROOTFS_DIR"

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: custom-proot.tar.gz
        tag: ${{ steps.get_next_tag.outputs.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}
