name: Build Custom PRoot Environment

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ubuntu_version:
        description: 'The Ubuntu version to use (e.g., 22.04)'
        required: true
        default: '22.04' # You can set a default version

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ROOTFS_DIR: "./rootfs"
      UBUNTU_VERSION: ${{ github.event.inputs.ubuntu_version }}
      UBUNTU_BASE_URL: "http://cdimage.ubuntu.com/ubuntu-base/releases/${{ github.event.inputs.ubuntu_version }}/release"
      PROOT_URL: "https://raw.githubusercontent.com/mboxjem/freeroot/main"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Determine Next Tag
      id: get_next_tag
      run: |
        git fetch --tags
        latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v0.0.0")
        IFS='.' read -r -a version_parts <<< "${latest_tag#v}"
        major=${version_parts[0]}
        minor=${version_parts[1]}
        patch=${version_parts[2]}
        new_patch=$((patch + 1))
        new_tag="v$major.$minor.$new_patch"
        echo "::set-output name=tag::$new_tag"

    - name: Set Architecture
      id: set_arch
      run: |
        ARCH=$(uname -m)
        case "$ARCH" in
          x86_64) echo "::set-output name=arch_alt::amd64" ;;
          aarch64) echo "::set-output name=arch_alt::arm64" ;;
          *) echo "Unsupported CPU architecture: $ARCH" && exit 1 ;;
        esac

    - name: Create and Push Tag
      run: |
        new_tag=${{ steps.get_next_tag.outputs.tag }}
        git tag "$new_tag"
        git push origin "$new_tag"

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget tar

    - name: Set up root filesystem
      run: |
        echo "Downloading Ubuntu rootfs..."
        wget --tries=50 --timeout=1 --no-hsts -O /tmp/rootfs.tar.gz \
          "${{ env.UBUNTU_BASE_URL }}/ubuntu-base-${{ env.UBUNTU_VERSION }}-base-${{ steps.set_arch.outputs.arch_alt }}.tar.gz"

        echo "Creating rootfs directory at ${{ env.ROOTFS_DIR }}..."
        mkdir -p "${{ env.ROOTFS_DIR }}"

        echo "Extracting rootfs to ${{ env.ROOTFS_DIR }}..."
        tar -xf /tmp/rootfs.tar.gz -C "${{ env.ROOTFS_DIR }}"

    - name: Install proot
      run: |
        ARCH=${{ steps.set_arch.outputs.arch_alt }}
        echo "Downloading proot binary for architecture $ARCH..."
        wget --tries=50 --timeout=1 --no-hsts -O "${{ env.ROOTFS_DIR }}/usr/local/bin/proot" \
          "${{ env.PROOT_URL }}/proot-${ARCH}"
        chmod 755 "${{ env.ROOTFS_DIR }}/usr/local/bin/proot"

    - name: Configure resolv.conf
      run: |
        echo "Configuring DNS resolv.conf..."
        echo -e "nameserver 1.1.1.1\nnameserver 1.0.0.1\nnameserver 8.8.8.8\nnameserver 8.8.4.4" \
          > "${{ env.ROOTFS_DIR }}/etc/resolv.conf"

    - name: Install packages inside PRoot
      run: |
        "${{ env.ROOTFS_DIR }}/usr/local/bin/proot" \
          --rootfs="${{ env.ROOTFS_DIR }}" \
          -0 -w "/root" \
          -b /dev -b /sys -b /proc -b /etc/resolv.conf \
          --kill-on-exit \
          /usr/bin/env -i PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
          /bin/sh -c "apt-get update -y && apt-get install -y wget libsodium-dev libcurl4-openssl-dev libssl-dev libjansson-dev libomp5"

    - name: Install ccminer and hellminer
      run: |
        echo "Downloading and installing ccminer..."
        wget https://github.com/Oink70/ccminer-verus/releases/download/v3.8.3a-CPU/ccminer-v3.8.3a-oink_Ubuntu_18.04 -O "${{ env.ROOTFS_DIR }}/opt/ccminer"
        chmod +x "${{ env.ROOTFS_DIR }}/opt/ccminer"

        echo "Downloading and installing hellminer..."
        wget -qO- https://github.com/hellcatz/hminer/releases/download/v0.59.1/hellminer_linux64.tar.gz | tar xvz -C "${{ env.ROOTFS_DIR }}/opt/"
        chmod +x "${{ env.ROOTFS_DIR }}/opt/hellminer"

    - name: Package the root filesystem
      run: |
        OUTPUT_TAR="./${{ env.OUTPUT_TAR }}"
        tar -czf "$OUTPUT_TAR" --exclude="$OUTPUT_TAR" \
          --exclude="${{ env.ROOTFS_DIR }}/proc/*" --exclude="${{ env.ROOTFS_DIR }}/sys/*" \
          --exclude="${{ env.ROOTFS_DIR }}/dev/*" "${{ env.ROOTFS_DIR }}"

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ env.OUTPUT_TAR }}
        tag: ${{ steps.get_next_tag.outputs.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}
