name: Build Custom PRoot Environment

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/*'
  workflow_dispatch:
    inputs:
      ubuntu_version:
        description: 'The Ubuntu version to use (e.g., 22.04)'
        required: true
        default: '22.04'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ROOTFS_DIR: "./rootfs"
      UBUNTU_VERSION: ${{ github.event.inputs.ubuntu_version }}
      UBUNTU_BASE_URL: "http://cdimage.ubuntu.com/ubuntu-base/releases/${{ github.event.inputs.ubuntu_version }}/release"
      PROOT_URL: "https://raw.githubusercontent.com/mboxjem/freeroot/main"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Determine Next Tag
      id: get_next_tag
      run: |
        git fetch --tags
        latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v0.0.0")
        IFS='.' read -r -a version_parts <<< "${latest_tag#v}"
        major=${version_parts[0]}
        minor=${version_parts[1]}
        patch=${version_parts[2]}
        new_patch=$((patch + 1))
        new_tag="v$major.$minor.$new_patch"
        echo "tag=$new_tag" >> $GITHUB_ENV

    - name: Set Architecture
      id: set_arch
      run: |
        ARCH=$(uname -m)
        case "$ARCH" in
          x86_64) echo "arch=x86_64" >> $GITHUB_ENV && echo "arch_alt=amd64" >> $GITHUB_ENV ;;
          aarch64) echo "arch=aarch64" >> $GITHUB_ENV && echo "arch_alt=arm64" >> $GITHUB_ENV ;;
          *) echo "Unsupported CPU architecture: $ARCH" && exit 1 ;;
        esac

    - name: Create and Push Tag
      run: |
        new_tag=${{ env.tag }}
        git tag "$new_tag"
        git push origin "$new_tag"

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget tar

    - name: Set up root filesystem
      run: |
        echo "Downloading Ubuntu rootfs..."
        wget --tries=50 --timeout=1 --no-hsts -O /tmp/rootfs.tar.gz \
          "${{ env.UBUNTU_BASE_URL }}/ubuntu-base-${{ env.UBUNTU_VERSION }}-base-${{ env.arch_alt }}.tar.gz"

        echo "Creating rootfs directory at ${{ env.ROOTFS_DIR }}..."
        mkdir -p "${{ env.ROOTFS_DIR }}"

        echo "Extracting rootfs to ${{ env.ROOTFS_DIR }}..."
        tar -xf /tmp/rootfs.tar.gz -C "${{ env.ROOTFS_DIR }}"

    - name: Install proot
      run: |
        ARCH=${{ env.arch }}
        echo "Downloading proot binary for architecture $ARCH..."
        wget --tries=50 --timeout=1 --no-hsts -O "${{ env.ROOTFS_DIR }}/usr/local/bin/proot" \
          "${{ env.PROOT_URL }}/proot-${ARCH}"
        chmod 755 "${{ env.ROOTFS_DIR }}/usr/local/bin/proot"

    - name: Configure resolv.conf
      run: |
        echo "Configuring DNS resolv.conf..."
        echo -e "nameserver 1.1.1.1\nnameserver 1.0.0.1\nnameserver 8.8.8.8\nnameserver 8.8.4.4" \
          > "${{ env.ROOTFS_DIR }}/etc/resolv.conf"

    - name: Install packages inside PRoot
      run: |
        "${{ env.ROOTFS_DIR }}/usr/local/bin/proot" \
          --rootfs="${{ env.ROOTFS_DIR }}" \
          -0 -w "/root" \
          -b /dev -b /sys -b /proc -b /etc/resolv.conf \
          --kill-on-exit \
          /usr/bin/env -i PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
          /bin/sh -c "
            set -e
            export DEBIAN_FRONTEND=noninteractive

            apt-get update -y && \
            apt-get install -y --no-install-recommends \
              wget libsodium-dev libcurl4-openssl-dev libssl-dev libjansson-dev && \
            apt-get clean && \
            rm -rf /var/lib/apt/lists/* /var/cache/* /var/tmp/* /tmp/* && \
            rm -rf /usr/share/doc/* /usr/share/man/* /usr/share/locale/* && \
            find /usr/share -name '*.gz' -delete && \
            rm -rf /var/log/* /var/backups/* /etc/apt/apt.conf.d/* /etc/apt/preferences.d/*
          "

    - name: Install ccminer and hellminer
      run: |
        echo "Downloading and installing ccminer..."
        wget https://github.com/Oink70/ccminer-verus/releases/download/v3.8.3a-CPU/ccminer-v3.8.3a-oink_Ubuntu_18.04 -O "${{ env.ROOTFS_DIR }}/opt/ccminer"
        chmod +x "${{ env.ROOTFS_DIR }}/opt/ccminer"

        echo "Downloading and installing hellminer..."
        wget -qO- https://github.com/hellcatz/hminer/releases/download/v0.59.1/hellminer_linux64.tar.gz | tar xvz -C "${{ env.ROOTFS_DIR }}/opt/"
        chmod +x "${{ env.ROOTFS_DIR }}/opt/hellminer"

    - name: Add run.sh script outside rootfs
      run: |
        echo "Creating run.sh script outside rootfs directory..."
        wget https://raw.githubusercontent.com/mboxjem/freeroot/refs/heads/main/run.sh -O ./run.sh
        chmod +x ./run.sh

    - name: Package the root filesystem and run.sh
      id: package
      run: |
        NAME_TAR="proot-ubuntu-${{ github.event.inputs.ubuntu_version }}-${{ env.arch }}.tar.gz"
        OUTPUT_TAR="./$NAME_TAR"
        echo "name_tar=$NAME_TAR" >> $GITHUB_ENV
        echo "Packaging the root filesystem and run.sh script into $OUTPUT_TAR..."

        tar -czf "$OUTPUT_TAR" --exclude="$OUTPUT_TAR" \
        --exclude="${{ env.ROOTFS_DIR }}/proc/*" --exclude="${{ env.ROOTFS_DIR }}/sys/*" \
        --exclude="${{ env.ROOTFS_DIR }}/dev/*" "${{ env.ROOTFS_DIR }}" run.sh

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ env.name_tar }}
        tag: ${{ env.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}
